api_platform:
    title: Api documentation for VonjyAina.MG
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
